// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 注册用户请求结构
type RegisterRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 注册用户返回结构
type RegisterResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 获取用户详情请求结构
type GetUserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{2}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 获取用户详情返回结构
type GetUserResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Signature            string   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Status               int64    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	IsDelete             int64    `protobuf:"varint,7,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{3}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetUserResponse) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *GetUserResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *GetUserResponse) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *GetUserResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetUserResponse) GetIsDelete() int64 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

func (m *GetUserResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetUserResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// 编辑用户请求结构
type SetUserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Signature            string   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Status               int64    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	IsDelete             int64    `protobuf:"varint,7,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Password             string   `protobuf:"bytes,10,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserRequest) Reset()         { *m = SetUserRequest{} }
func (m *SetUserRequest) String() string { return proto.CompactTextString(m) }
func (*SetUserRequest) ProtoMessage()    {}
func (*SetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{4}
}

func (m *SetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserRequest.Unmarshal(m, b)
}
func (m *SetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserRequest.Marshal(b, m, deterministic)
}
func (m *SetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserRequest.Merge(m, src)
}
func (m *SetUserRequest) XXX_Size() int {
	return xxx_messageInfo_SetUserRequest.Size(m)
}
func (m *SetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserRequest proto.InternalMessageInfo

func (m *SetUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SetUserRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *SetUserRequest) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *SetUserRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SetUserRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *SetUserRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SetUserRequest) GetIsDelete() int64 {
	if m != nil {
		return m.IsDelete
	}
	return 0
}

func (m *SetUserRequest) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *SetUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 编辑用户返回结构
type SetUserResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserResponse) Reset()         { *m = SetUserResponse{} }
func (m *SetUserResponse) String() string { return proto.CompactTextString(m) }
func (*SetUserResponse) ProtoMessage()    {}
func (*SetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{5}
}

func (m *SetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserResponse.Unmarshal(m, b)
}
func (m *SetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserResponse.Marshal(b, m, deterministic)
}
func (m *SetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserResponse.Merge(m, src)
}
func (m *SetUserResponse) XXX_Size() int {
	return xxx_messageInfo_SetUserResponse.Size(m)
}
func (m *SetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserResponse proto.InternalMessageInfo

func (m *SetUserResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

// 注销用户请求结构
type LogOutRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogOutRequest) Reset()         { *m = LogOutRequest{} }
func (m *LogOutRequest) String() string { return proto.CompactTextString(m) }
func (*LogOutRequest) ProtoMessage()    {}
func (*LogOutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{6}
}

func (m *LogOutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogOutRequest.Unmarshal(m, b)
}
func (m *LogOutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogOutRequest.Marshal(b, m, deterministic)
}
func (m *LogOutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogOutRequest.Merge(m, src)
}
func (m *LogOutRequest) XXX_Size() int {
	return xxx_messageInfo_LogOutRequest.Size(m)
}
func (m *LogOutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogOutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogOutRequest proto.InternalMessageInfo

func (m *LogOutRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 注销用户返回结构
type LogOutResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogOutResponse) Reset()         { *m = LogOutResponse{} }
func (m *LogOutResponse) String() string { return proto.CompactTextString(m) }
func (*LogOutResponse) ProtoMessage()    {}
func (*LogOutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{7}
}

func (m *LogOutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogOutResponse.Unmarshal(m, b)
}
func (m *LogOutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogOutResponse.Marshal(b, m, deterministic)
}
func (m *LogOutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogOutResponse.Merge(m, src)
}
func (m *LogOutResponse) XXX_Size() int {
	return xxx_messageInfo_LogOutResponse.Size(m)
}
func (m *LogOutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogOutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogOutResponse proto.InternalMessageInfo

func (m *LogOutResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

// 登陆请求结构
type LoginRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{8}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 登陆返回结构
type LoginResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{9}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *LoginResponse) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *LoginResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "mall.rpc.user.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "mall.rpc.user.RegisterResponse")
	proto.RegisterType((*GetUserRequest)(nil), "mall.rpc.user.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "mall.rpc.user.GetUserResponse")
	proto.RegisterType((*SetUserRequest)(nil), "mall.rpc.user.SetUserRequest")
	proto.RegisterType((*SetUserResponse)(nil), "mall.rpc.user.SetUserResponse")
	proto.RegisterType((*LogOutRequest)(nil), "mall.rpc.user.LogOutRequest")
	proto.RegisterType((*LogOutResponse)(nil), "mall.rpc.user.LogOutResponse")
	proto.RegisterType((*LoginRequest)(nil), "mall.rpc.user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "mall.rpc.user.LoginResponse")
}

func init() {
	proto.RegisterFile("pb/user.proto", fileDescriptor_c4f917211a932270)
}

var fileDescriptor_c4f917211a932270 = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0x3d, 0x6f, 0xd4, 0x40,
	0x10, 0x25, 0xce, 0xc5, 0xb1, 0x47, 0x9c, 0x0f, 0x6d, 0x81, 0x2c, 0xe7, 0x2e, 0x89, 0x5c, 0x85,
	0xc6, 0x91, 0xa0, 0xa4, 0x4a, 0x14, 0x29, 0x12, 0x3a, 0x84, 0x64, 0x2b, 0x0d, 0xcd, 0x69, 0x7d,
	0x5e, 0x59, 0x2b, 0x7c, 0x5e, 0xb3, 0x1f, 0x50, 0x53, 0xf0, 0xaf, 0x29, 0xd0, 0xae, 0x3f, 0x2e,
	0xf6, 0x9d, 0x0d, 0x15, 0x12, 0xe5, 0xcc, 0x7b, 0xfb, 0xfc, 0x76, 0xfc, 0x66, 0x61, 0x5e, 0xa5,
	0xb7, 0x4a, 0x10, 0x1e, 0x55, 0x9c, 0x49, 0x86, 0xe6, 0x3b, 0x5c, 0x14, 0x11, 0xaf, 0xb6, 0x91,
	0x6e, 0x86, 0x18, 0x16, 0x31, 0xc9, 0xa9, 0x90, 0x84, 0xc7, 0xe4, 0xab, 0x22, 0x42, 0xa2, 0xd7,
	0x60, 0xef, 0x58, 0x4a, 0x0b, 0xe2, 0x9f, 0x5c, 0x9f, 0xdc, 0xb8, 0x71, 0x53, 0xa1, 0x00, 0x9c,
	0x92, 0x6e, 0xbf, 0x94, 0x78, 0x47, 0x7c, 0xcb, 0x20, 0x5d, 0xad, 0xb1, 0x0a, 0x0b, 0xf1, 0x9d,
	0xf1, 0xcc, 0x3f, 0xad, 0xb1, 0xb6, 0x0e, 0x43, 0x78, 0xb5, 0xff, 0x84, 0xa8, 0x58, 0x29, 0x08,
	0xf2, 0xc0, 0xa2, 0x99, 0xd1, 0x3f, 0x8d, 0x2d, 0x9a, 0x85, 0xd7, 0xe0, 0x3d, 0x12, 0xf9, 0x24,
	0xf6, 0x2e, 0x86, 0x8c, 0x9f, 0x16, 0x2c, 0x3a, 0xca, 0x71, 0x95, 0x49, 0x87, 0x2b, 0x00, 0xfc,
	0x0d, 0x4b, 0xcc, 0x37, 0x8a, 0x17, 0x8d, 0x47, 0xb7, 0xee, 0x3c, 0xf1, 0xe2, 0xd9, 0xa5, 0x67,
	0xbd, 0x4b, 0x2f, 0xc1, 0x15, 0x34, 0x2f, 0xb1, 0x54, 0x9c, 0xf8, 0x67, 0xf5, 0xa9, 0xae, 0xa1,
	0x4f, 0x09, 0x89, 0xa5, 0x12, 0xbe, 0x6d, 0x4c, 0x34, 0x15, 0xba, 0x00, 0x97, 0x8a, 0x4d, 0x46,
	0x0a, 0x22, 0x89, 0x7f, 0x6e, 0x20, 0x87, 0x8a, 0x07, 0x53, 0x6b, 0x27, 0x5b, 0x4e, 0xb0, 0x24,
	0xd9, 0x06, 0x4b, 0xdf, 0xa9, 0x35, 0x9b, 0xce, 0x9d, 0xd4, 0xb0, 0xaa, 0xb2, 0x16, 0x76, 0x6b,
	0xb8, 0xe9, 0xdc, 0xc9, 0xf0, 0x87, 0x05, 0x5e, 0x32, 0x39, 0xaa, 0xff, 0x67, 0x0c, 0x13, 0xf7,
	0xec, 0x25, 0x0a, 0x06, 0x89, 0x7a, 0x03, 0x8b, 0x64, 0x10, 0x85, 0xbd, 0x05, 0x3d, 0x07, 0xa7,
	0xb5, 0x10, 0x5e, 0xc1, 0x7c, 0xcd, 0xf2, 0x4f, 0x4a, 0x8e, 0xe5, 0xea, 0x06, 0xbc, 0x96, 0xf0,
	0x07, 0xa9, 0x7b, 0x78, 0xb9, 0x66, 0x39, 0x2d, 0xff, 0x62, 0x4f, 0x3a, 0xe7, 0xd6, 0xc0, 0x39,
	0x37, 0x76, 0xb4, 0xc6, 0x3f, 0x8b, 0xf0, 0xdb, 0x5f, 0x16, 0xcc, 0xf4, 0xac, 0xd0, 0x47, 0x70,
	0xda, 0x45, 0x44, 0x97, 0x51, 0xef, 0x1d, 0x88, 0x06, 0x8f, 0x40, 0x70, 0x35, 0x8a, 0xd7, 0xc6,
	0xc3, 0x17, 0xe8, 0x03, 0x9c, 0x37, 0x0b, 0x89, 0x56, 0x03, 0x76, 0x7f, 0x97, 0x83, 0xcb, 0x31,
	0xf8, 0xb9, 0x56, 0x32, 0xa2, 0x95, 0x4c, 0x6b, 0x25, 0x07, 0x5a, 0x8f, 0x60, 0xaf, 0x59, 0xce,
	0x94, 0x44, 0xcb, 0x01, 0xb7, 0x97, 0x84, 0x60, 0x35, 0x82, 0x76, 0x42, 0x0f, 0x70, 0x66, 0x7e,
	0x16, 0xba, 0x38, 0x64, 0x76, 0x31, 0x08, 0x96, 0xc7, 0xc1, 0x56, 0xe5, 0xde, 0xfe, 0x3c, 0xbb,
	0x7d, 0x5f, 0xa5, 0xa9, 0x6d, 0xde, 0xdf, 0x77, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x99, 0x57,
	0x64, 0x6b, 0x90, 0x05, 0x00, 0x00,
}
