// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: lottery/v1/lottery.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LotteryClient is the client API for Lottery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LotteryClient interface {
	FindLottery(ctx context.Context, in *FindLotteryReq, opts ...grpc.CallOption) (*LotteryResp, error)
	CreateLottery(ctx context.Context, in *CreateLotteryReq, opts ...grpc.CallOption) (*LotteryResp, error)
}

type lotteryClient struct {
	cc grpc.ClientConnInterface
}

func NewLotteryClient(cc grpc.ClientConnInterface) LotteryClient {
	return &lotteryClient{cc}
}

func (c *lotteryClient) FindLottery(ctx context.Context, in *FindLotteryReq, opts ...grpc.CallOption) (*LotteryResp, error) {
	out := new(LotteryResp)
	err := c.cc.Invoke(ctx, "/lottery.api.v1.Lottery/FindLottery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryClient) CreateLottery(ctx context.Context, in *CreateLotteryReq, opts ...grpc.CallOption) (*LotteryResp, error) {
	out := new(LotteryResp)
	err := c.cc.Invoke(ctx, "/lottery.api.v1.Lottery/CreateLottery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LotteryServer is the server API for Lottery service.
// All implementations must embed UnimplementedLotteryServer
// for forward compatibility
type LotteryServer interface {
	FindLottery(context.Context, *FindLotteryReq) (*LotteryResp, error)
	CreateLottery(context.Context, *CreateLotteryReq) (*LotteryResp, error)
	mustEmbedUnimplementedLotteryServer()
}

// UnimplementedLotteryServer must be embedded to have forward compatible implementations.
type UnimplementedLotteryServer struct {
}

func (UnimplementedLotteryServer) FindLottery(context.Context, *FindLotteryReq) (*LotteryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindLottery not implemented")
}
func (UnimplementedLotteryServer) CreateLottery(context.Context, *CreateLotteryReq) (*LotteryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLottery not implemented")
}
func (UnimplementedLotteryServer) mustEmbedUnimplementedLotteryServer() {}

// UnsafeLotteryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LotteryServer will
// result in compilation errors.
type UnsafeLotteryServer interface {
	mustEmbedUnimplementedLotteryServer()
}

func RegisterLotteryServer(s grpc.ServiceRegistrar, srv LotteryServer) {
	s.RegisterService(&Lottery_ServiceDesc, srv)
}

func _Lottery_FindLottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindLotteryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).FindLottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lottery.api.v1.Lottery/FindLottery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).FindLottery(ctx, req.(*FindLotteryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lottery_CreateLottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLotteryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServer).CreateLottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lottery.api.v1.Lottery/CreateLottery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServer).CreateLottery(ctx, req.(*CreateLotteryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Lottery_ServiceDesc is the grpc.ServiceDesc for Lottery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lottery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lottery.api.v1.Lottery",
	HandlerType: (*LotteryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindLottery",
			Handler:    _Lottery_FindLottery_Handler,
		},
		{
			MethodName: "CreateLottery",
			Handler:    _Lottery_CreateLottery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lottery/v1/lottery.proto",
}
